### ISSUE TITLE
Add support for userdb

### ISSUE THREAD

**Issue by bigon** [SELinuxProject/refpolicy#246]
Hello,

With the recent versions of systemd, there is a new `userdb` component added.

`libnss-systemd` is now trying to connect to a socket located in `/run/systemd/userdb/` that meas that any domain (including a user one) that should resolve user/group id might try to connect to it.

There is also an optional daemon running

Fedora policy already has support for this that adds custom types.

**Comment by bauen1** [comment]
> There is also an optional daemon running

Which daemon ?

**Comment by doverride** [comment]
Laurent Bigonville <notifications@github.com> writes:

> Hello,
>
> With the recent versions of systemd, there is a new userdb component added.
>
> libnss-systemd is now trying to connect to a socket located in /run/systemd/userdb/ that meas that any domain (including a user one)
> that should resolve user/group id might try to connect to it.
>
> There is also an optional daemon running
>
> Fedora policy already has support for this that adds custom types.

There are currently 3 sockets and 1 symlink in /run/user/userdb if you have
systemd-homed enabled:

io..systemd.DynamicUser - This is the new way to resolve dynamic users
previously this was done by dbus chatting with pid1 (init_t)

not sure if suppose for that was ever implemented in refpolicy. NSS
passwd/group clients need to be able to list /run/systemd/userdb and write
this socket to unix stream connect to init_t to be able to resolve
dynamic uids/gids (along with needing to get attributes of
/etc/systemd/dont-synthesize-nobody)

So since in refpolicy there is no distinction between glibc nss
passwd/group and glibc nss hosts (and all the others like services),
callers of auth_use_nsswitch() should be allowed to resolve dynamic
users this way (dbus is no longer used for this which is nice since now
you dont need to be dbus client anymore just for glibc passwd/group (you
still need it for glibc nss hosts though (for mymachines and myhostname) 

Then there is io.systemd.Home, this is new for systemd-homed and
pam-systemd-home, nss passwd group clients (auth_use_nswitch() callers
)should also be able to list /run/systemd/userdb and write this
io.systemd.Home socket to connect to systemd-homed (if its enabled and
running) to resolve users managed with homed (i guess)

lastly theres io.systemd.Multiplexer (and a symlink
io.systemd.NameServiceSwitch pointing to it). As far as i know with the
exception of userdbctl (userdbctl uses it to connect to
systemd-userdbd), only "pam clients" need to be able list
/run/systemd/userdb AFAIK, read the io.systemd.NameServiceSwitch symlink and
write the io.systemd.Multiplexer socket to unix stream connect with
systemd-userdbd (if it is enabeled and running)

userdb and systemd-home are in theory optional. The
io.systemd.DynamicUser functionality is probably mandatory.

systemd-homed, systemd and systemd-userdbd maintain the sockets in
/run/systemd/userdbd so i would argue that a private type for
/run/systemd/userdb makes sense

Whether it makes sense to label each sock file with a private type is
debatable i think. In my personal policy I label all of
/run/systemd/userdb with a single private type, and i rely on
differentiation with the "unix_stream_socket connectto" target access
vector, as each socket has a different target (init_t systemd_homed_t
systemd_userdbd_t)

There are various manual pages enclosed with systemd describing the
sockets and the pam_systemd_home module is also documented

>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 
gpg --locate-keys dominick.grift@defensec.nl
Key fingerprint = FCD2 3660 5D6B 9D27 7FC6  E0FF DA7E 521F 10F6 4098
https://sks-keyservers.net/pks/lookup?op=get&search=0xDA7E521F10F64098
Dominick Grift

**Comment by bigon** [comment]
Indeed ATM, debian doesn't have userdb and homed built, so what I've experienced is only call to the `io.systemd.DynamicUser` socket from other domains

**Comment by doverride** [comment]
Laurent Bigonville <notifications@github.com> writes:

> Indeed ATM, debian doesn't have userdb and homed built, so what I've experienced is only call to the io.systemd.DynamicUser socket
> from other domains

Good call by Debian. userdb/homed is another one of poetterings
escapades.

>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 
gpg --locate-keys dominick.grift@defensec.nl
Key fingerprint = FCD2 3660 5D6B 9D27 7FC6  E0FF DA7E 521F 10F6 4098
https://sks-keyservers.net/pks/lookup?op=get&search=0xDA7E521F10F64098
Dominick Grift

**Comment by fishilico** [comment]
> Good call by Debian. userdb/homed is another one of poetterings escapades.

I agree. These changes were introduced in the latest release (systemd 245) and are described in https://github.com/systemd/systemd/blob/v245/NEWS#L27-L65. I have seen this on Arch Linux but have not found time yet to adapt the refpolicy for these new features.
