### ISSUE TITLE
StyleGuide: Order of require statements

### ISSUE THREAD

**Issue by cgzones** [SELinuxProject/refpolicy#254]
The [style guide](https://github.com/SELinuxProject/refpolicy/wiki/StyleGuide) does not contain any information about the order (of kinds and names) in require blocks.

Is there a preferred order, should an order be followed, or is it indifferent?

Seems like currently the order for required kinds is mostly (but not completely):
```
attribute -> attribute_role -> type -> class -> role
```

p.s.:
My personal favourite order is
```
bool -> class -> role -> attribute_role -> attribute -> type
```

**Comment by dburgener** [comment]
IMHO require blocks are so short, I'm not sure that having a consistent order matters all that much.  If I had my perfect world though, I'd prefer to have booleans and classes together either at the beginning or end, in order to help call attention to the uncommon case.

For te file declarations the style guide specifies `bool -> attribute -> type`, so I would see a lot of advantage in keeping that relative order consistent if a rule were defined for require blocks.

**Comment by pebenito** [comment]
There is no preferred order.
