### ISSUE TITLE
Proposal: add an attribute to remove default ioctl access

### ISSUE THREAD

**Issue by DemiMarie** [SELinuxProject/refpolicy#327]
#76 (SELinux ioctl allowlist) was (understandably) closed, as it would have required a large amount of effort and had a high risk of breakage.

That said, I would still like to be able to restrict the ioctls a process can use via SELinux.  This can be done by means of an attribute.  Types with that attribute are given xperm rules that block all ioctls.  Any needed ioctls can be allowed by user-provided xperm rules.

I would be willing to write a PR for this, if upstream is interested.

**Comment by pebenito** [comment]
Can you provide some snippets of policy to better illustrate how this would work? Preferrably the interface(s) that would implement this? I want to make sure I understand what you're proposing.

**Comment by DemiMarie** [comment]
So my idea was something like

```
attribute ioctl_restricted_type;

allowxperm ioctl_restricted_type device_node:alg_socket ioctl {};
# long list of empty xperm entries here

interface(`restrict_ioctls',`
	gen_require(``attribute ioctl_restricted_type;'')`
	typeattribute ioctl_restricted_type '$1
')
```

**Comment by pebenito** [comment]
Conceptually I don't have a problem with this, but it seems like the implementation will be messy and require many interfaces to preserve encapsulation since you need to access attributes like `file_type`, `domain`, etc.

The real answer for this would be a high level policy language that supports deleting perms from existing rules. Sadly that doesn't exist yet.
