### ISSUE TITLE
disable booleans

### ISSUE THREAD

**Issue by embexus** [SELinuxProject/refpolicy#354]
is there anyway to completely disable booleans support in refpolicy ?

thanks.

**Comment by pebenito** [comment]
If you mean completely remove them from the policy, then no.

**Comment by embexus** [comment]
No what I meant is disable completely switching on/off booleans or have an empty list of tunable booleans on my system.

**Comment by doverride** [comment]
embexus <notifications@github.com> writes:

> No what I meant is disable completely switching on/off booleans or have an empty list of tunable
> booleans on my system.

This is an interesting topic. Booleans suck because theyre mostly
meaningless in systems with monolithic policy (where policy is usually
immutable at runtime anyway) and only generally useful in a modular policy.

There is a build-time option called "preserve tunables" which can be
used to build policy with tunables preserved as booleans (which implies
that you can disable booleans if you just dont preserve the tunables)

Not sure if and to what extend refpolicy supports that feature. I do
leverage in my personal policy, where when i build modular policy I
preserve tunables, and when I build monolithic policy I do not preserve
tunables and treat them solely as build-time tunables. 

>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 
gpg --locate-keys dominick.grift@defensec.nl
Key fingerprint = FCD2 3660 5D6B 9D27 7FC6  E0FF DA7E 521F 10F6 4098
https://sks-keyservers.net/pks/lookup?op=get&search=0xDA7E521F10F64098
Dominick Grift

**Comment by pebenito** [comment]
Agreed that tunables make more sense as link/build time options.

We have some secure_mode* booleans that disable various things to tighten security. If we had one called something like `secure_mode_setbool` that prevented changing any booleans (and possibly disable seteforce too) would that fit your needs? If you set that to default to True then you would lock in all of the boolean states.

**Comment by embexus** [comment]
@pebenito that would be great if we have the **secure_mode_setbool** option

**Comment by pebenito** [comment]
Please see if this will work for you. I decided to make `secure_mode_setbool` not disable setenforce permissions, as the stronger `secure_mode_policyload` does that.

**Comment by pebenito** [comment]
Let's make sure it's not a code bug, since it shouldn't matter which tool you use. If you do `cat /sys/fs/selinux/booleans/user_ping` you should see two values. The first value is the actual Boolean value and the second is the pending value.

**Comment by pebenito** [comment]
I plan to do an additional change to block even setting the pending value, but I want to make sure what we have is working as expected first.
