### ISSUE TITLE
Consider removing MCS categories from default users contexts in seusers

### ISSUE THREAD

**Issue by 0xC0ncord** [SELinuxProject/refpolicy#453]
We should consider changing the default seusers to not include MCS categories since #415 means that the user domains no longer need them to access resources with MCS categories.

cc @doverride

**Comment by pebenito** [comment]
I don't follow what you're suggesting.

**Comment by 0xC0ncord** [comment]
On systems where the policy has only one sensitivity level (s0), why do we have users logging in with `s0-s0` instead of just `s0`?

**Comment by doverride** [comment]
I am suggesting that clearances should not be used in modern MCS policy.

So the above should look like:

```
# semanage login -l
Login Name           SELinux User         MLS/MCS Range        Service

__default__          user_u               s0-s0                *
root                 root                 s0-s0       *
concord              staff_u              s0-s0       *
```

Also any "ranged_transitions" in `ifdef_MCS` blocks should be reviewed and likely be removed. There is no point to clearances in MCS policy because the entities that are mcs constrained generally should not have the ability to use a clearance (they get some compartments associated and they're expected to stay put)

**Comment by pebenito** [comment]
> On systems where the policy has only one sensitivity level (s0), why do we have users logging in with `s0-s0` instead of just `s0`?

`s0-s0` == `s0` in terms of ranges.

**Comment by pebenito** [comment]
> I am suggesting that clearances should not be used in modern MCS policy.

[...]

> Also any "ranged_transitions" in `ifdef_MCS` blocks should be reviewed and likely be removed. There is no point to clearances in MCS policy because the entities that are mcs constrained generally should not have the ability to use a clearance (they get some compartments associated and they're expected to stay put)

Makes sense.
