### ISSUE TITLE
Is there any way to start a process with lowered security level?

### ISSUE THREAD

**Issue by serega990306** [SELinuxProject/refpolicy#463]
Hello, I've created a Selinux user with MLS a range s0-s1:
`setest01_u      user       s0         s0-s1`
And every process the user starts takes the range s0-s1:
`setest01_u:myrole_r:myrole_t:s0-s1 15786 tty5    00:00:00 Xwayland`
How can I start this process with level s0 or any other process with level s1? Is this even possible?

**Comment by doverride** [comment]
Sergei Petrov ***@***.***> writes:

> Hello, I've created a Selinux user with MLS a range s0-s1:
> setest01_u user s0 s0-s1
> And every process the user starts takes the range s0-s1:
> setest01_u:myrole_r:myrole_t:s0-s1 15786 tty5 00:00:00 Xwayland
> How can I start this process with level s0 or any other process with level s1? Is this even
> possible?

I am not good with MLS but there are various way's to address labeling.

PAM (pam_selinux has options that allow you to set (process) labels when you log in)
`runcon` allows you to run a process with a given label
`newrole` allows you to change (process) labels

and then there are also automatic (process) transitions that could be
defined (and i might have overlooked other aspects)

But yes, AFAIK, aslong as you have the appropriate clearance you should be able to set
the current security level.

>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you are subscribed to this thread.
>

-- 
gpg --locate-keys ***@***.***
Key fingerprint = FCD2 3660 5D6B 9D27 7FC6  E0FF DA7E 521F 10F6 4098
Dominick Grift

**Comment by serega990306** [comment]
I think, in this situation, it is correct to use a range_transition statement. I've tried this:
```
range_transition myrole_t xdm_t:unix_stream_socket s0;
range_transition myrole_dbusd_t xdm_t:unix_stream_socket s0;
range_transition myrole_t xserver_t:process s0;
range_transition myrole_systemd_t xserver_t:unix_stream_socket s0;
```
This example doesn't work. I still get:
`setest01_u:myrole_r:myrole_t:s0-s1 2089 tty2     00:00:00 Xwayland`
I do not know what types to use.

**Comment by doverride** [comment]
This is pretty complicated matter, but i think your approach is not optimal.

First docs: https://github.com/SELinuxProject/selinux-notebook/blob/main/src/mls_statements.md#range_transition

So for example I believe at least this would be wrong:
```
range_transition myrole_t xserver_t:process s0;
```
and should probably be something like this:
```
range_transition myrole_t xserver_exec_t:process s0;
```
but even then I think using `runcon` might be easier/better (not sure though)
```
runcon -l s0-s0 -- startx
```
The question is though whether this is what really you want.

You could (i guess) for example just run the window manager with s0-s1 and then from there for example run xterm with s0 or s1 etc using `runcon`.

You can in theory also configure pam selinux/pam_namespace so that your desktop manager will prompt you for a context to use (although that probably currently does not work properly anymore)

Using MLS in a desktop environment (and in general) is hard (and currently probably buggy) because there are so many interactions in such an environment.

So you're entering a world of pain

**Comment by pebenito** [comment]
Is starting the entire user session at `s0` the desired behavior? That would fix your issue. You can do that by adjusting your seuser config (semanage login) to login at that level.
